"""
SetFit Training Data for Intent Classification
==============================================

Training data for 8 intent classes:
- casual: Greetings, thanks, complaints, random questions, off-topic queries
- visa_query: Questions about visa requirements
- follow_up: Providing nationality/destination when asked (country names, nationalities)
- booking: Flight/hotel booking requests (COMING SOON)
- ticket_change: Ticket modifications/refunds (COMING SOON)
- flight_info: General flight/airline questions (COMING SOON)
- clarification_origin: User indicating a country is their nationality/origin
- clarification_destination: User indicating a country is their destination
"""

TRAINING_DATA = [

# =========================================================================
# CASUAL (64 examples)
# =========================================================================
("hi", "casual"),
("hello", "casual"),
("hey there", "casual"),
("good morning", "casual"),
("whats up", "casual"),
("bye", "casual"),
("goodbye", "casual"),
("see you later", "casual"),
("take care", "casual"),
("thanks a lot", "casual"),

("whats your name", "casual"),
("are you a robot", "casual"),
("how does this work", "casual"),
("what can you do", "casual"),
("who made you", "casual"),
("are you even real", "casual"),
("why are you so slow today", "casual"),
("why are you answering like that", "casual"),
("explain yourself", "casual"),
("do you have feelings", "casual"),

("you are the worst", "casual"),
("terrible service", "casual"),
("are you sure about that", "casual"),
("i dont think thats right", "casual"),
("this system makes no sense", "casual"),
("what is this nonsense", "casual"),
("bro what is this", "casual"),
("youre confusing me", "casual"),
("you answer too fast lol", "casual"),
("that's not what i meant", "casual"),

("i dont know", "casual"),
("not sure yet", "casual"),
("let me think first", "casual"),
("i need to think", "casual"),
("maybe later", "casual"),
("idk man", "casual"),
("hmm", "casual"),
("i guess", "casual"),
("maybe", "casual"),
("i have no idea", "casual"),

("why is the sky blue", "casual"),
("how do i start a business", "casual"),
("how do i cook biryani", "casual"),
("who won the football match yesterday", "casual"),
("explain minecraft speedrunning", "casual"),
("teach me programming", "casual"),
("why do cats sleep so much", "casual"),
("how do i lose weight fast", "casual"),
("what's the weather like today", "casual"),
("why does coffee keep me awake", "casual"),
("how do i improve my memory", "casual"),
("who invented the light bulb", "casual"),

("how much baggage is allowed in my relationship", "casual"),
("can i board the train of success", "casual"),
("when does my motivation depart", "casual"),
("is my life economy class or business class", "casual"),
("india is where my favourite actor is from", "casual"),
("turkey is what im cooking tonight", "casual"),
("france is my new laptop wallpaper", "casual"),
("canada is the brand of my jacket", "casual"),
("dubai perfume smells good", "casual"),
("can i carry emotional baggage into this conversation", "casual"),
("my confidence just checked in", "casual"),
("my energy took off this morning", "casual"),


# =========================================================================
# VISA_QUERY (64 examples)
# =========================================================================
("do i need a visa", "visa_query"),
("visa requirements", "visa_query"),
("what visa do i need", "visa_query"),
("is visa required", "visa_query"),
("can i travel without visa", "visa_query"),
("do i need visa or evisa", "visa_query"),
("what type of visa should i get", "visa_query"),
("visa on arrival available", "visa_query"),
("i want to go to dubai", "visa_query"),
("planning to visit singapore", "visa_query"),

("going to japan next month", "visa_query"),
("trip to thailand", "visa_query"),
("traveling to france", "visa_query"),
("i want to travel to germany", "visa_query"),
("planning a vacation to italy", "visa_query"),
("visiting united states soon", "visa_query"),
("i need to go to canada", "visa_query"),
("flying to australia next week", "visa_query"),
("what do i need to enter usa", "visa_query"),
("entry requirements for uk", "visa_query"),

("can pakistanis visit turkey", "visa_query"),
("do americans need visa for japan", "visa_query"),
("requirements for indian passport holders", "visa_query"),
("what documents do i need for travel", "visa_query"),
("how do i apply for visa", "visa_query"),
("where can i get visa information", "visa_query"),
("im pakistani and want to visit dubai", "visa_query"),
("as an indian citizen can i visit singapore", "visa_query"),
("check visa for me", "visa_query"),
("tell me about visa process", "visa_query"),

("is visa on arrival available for vietnam", "visa_query"),
("can a filipino enter jordan without visa", "visa_query"),
("does kenyan passport need visa for spain", "visa_query"),
("do bangladeshi citizens need visa for oman", "visa_query"),
("is transit visa required for hong kong", "visa_query"),
("is evisa possible for kenya", "visa_query"),
("can i enter germany with expired schengen", "visa_query"),
("requirements for nepali citizens visiting qatar", "visa_query"),
("what entry rules apply for japan", "visa_query"),
("does my nationality need an evisa", "visa_query"),

("can sri lankans travel to uae visa free", "visa_query"),
("visa policy for mexican passport holders", "visa_query"),
("tourist visa requirements for egypt", "visa_query"),
("do i need visa for layover in beijing", "visa_query"),
("how do moroccans enter turkey", "visa_query"),
("visa requirements for tunisian citizens", "visa_query"),
("is schengen visa needed for poland trip", "visa_query"),
("what documents needed for italy visit", "visa_query"),
("evisa rules for malaysia", "visa_query"),
("do lebanese need visa for dubai", "visa_query"),

("who needs visa for south korea", "visa_query"),
("visiting qatar what visa needed", "visa_query"),
("saudi citizens visa rules for indonesia", "visa_query"),
("how to get tourist visa for turkey", "visa_query"),
("do i require visa to enter brazil", "visa_query"),
("can georgian enter uk without visa", "visa_query"),
("visa duration for thailand visit", "visa_query"),
("documents needed to enter vietnam", "visa_query"),
("what visa for argentina visit", "visa_query"),
("do i need entry permit for russia", "visa_query"),
("visa free countries for my passport", "visa_query"),
("can nigerians enter morocco without visa", "visa_query"),
("how long can i stay in dubai without visa", "visa_query"),
("tourist visa application for usa", "visa_query"),


# =========================================================================
# FOLLOW_UP (64 examples)
# =========================================================================
("pakistani", "follow_up"),
("indian", "follow_up"),
("american", "follow_up"),
("british", "follow_up"),
("canadian", "follow_up"),
("australian", "follow_up"),
("im pakistani", "follow_up"),
("i am from pakistan", "follow_up"),
("i hold indian passport", "follow_up"),
("american citizen", "follow_up"),

("british national", "follow_up"),
("i am a citizen of canada", "follow_up"),
("my nationality is german", "follow_up"),
("im from the united states", "follow_up"),
("dubai", "follow_up"),
("singapore", "follow_up"),
("japan", "follow_up"),
("turkey", "follow_up"),
("france", "follow_up"),
("germany", "follow_up"),

("what about turkey", "follow_up"),
("and for germany", "follow_up"),
("how about usa", "follow_up"),
("what about japan", "follow_up"),
("and singapore", "follow_up"),
("also check thailand", "follow_up"),
("and what about malaysia", "follow_up"),
("check indonesia too", "follow_up"),
("try australia as well", "follow_up"),
("also qatar please", "follow_up"),

("lebanese", "follow_up"),
("somali", "follow_up"),
("egyptian", "follow_up"),
("nigerian", "follow_up"),
("ethiopian", "follow_up"),
("italian", "follow_up"),
("spanish", "follow_up"),
("nepali", "follow_up"),
("bangladeshi", "follow_up"),
("sri lankan", "follow_up"),

("im moroccan", "follow_up"),
("im from kenya", "follow_up"),
("i have turkish passport", "follow_up"),
("i hold a philippine passport", "follow_up"),
("my passport is jordanian", "follow_up"),
("my nationality is sudanese", "follow_up"),
("im from qatar", "follow_up"),
("im from bahrain", "follow_up"),
("im from oman", "follow_up"),
("im from saudi", "follow_up"),

("iraqi", "follow_up"),
("syrian", "follow_up"),
("palestinian", "follow_up"),
("brazilian", "follow_up"),
("argentinian", "follow_up"),
("mexican", "follow_up"),
("chinese", "follow_up"),
("thai", "follow_up"),
("south african", "follow_up"),
("vietnamese", "follow_up"),
("also check portugal", "follow_up"),
("and spain too", "follow_up"),
("try italy", "follow_up"),
("what about greece", "follow_up"),


# =========================================================================
# BOOKING (64 examples)
# =========================================================================
("I want to book a flight to Dubai", "booking"),
("Whats the cheapest flight to London next week", "booking"),
("Book me a ticket for tomorrow morning", "booking"),
("I need 2 return tickets from Manchester to Islamabad", "booking"),
("Can you find flights under 400 to Turkey in March", "booking"),
("Wanna book a flight for my mom to Pakistan ASAP", "booking"),
("Im looking for the lowest fare to Saudi Arabia next month", "booking"),
("Can you reserve a hotel for 3 nights in Istanbul", "booking"),

("Need a flight and hotel package for Malaysia", "booking"),
("Book me anything to Dubai this weekend cheap one", "booking"),
("I wanna fly to Doha but only evening flights", "booking"),
("Search flights from LHR to JFK with 1 bag", "booking"),
("Get me the best price for a one way ticket to India", "booking"),
("Can you check flights from Birmingham to Lahore on 12 Feb", "booking"),
("I need 4 tickets for my family to Jeddah", "booking"),
("Need a flight with short layovers only", "booking"),

("Find me the earliest flight to Qatar tomorrow", "booking"),
("I wanna book business class for my boss to Dubai", "booking"),
("Can you check hotel prices in Dubai Marina", "booking"),
("Looking for a cheap return flight to Italy", "booking"),
("Find me flights anywhere warm next week", "booking"),
("Need 3 rooms in Makkah from 10 to 15 March", "booking"),
("Book flight London to Karachi economy with 30kg", "booking"),
("Can you arrange a full package for Umrah", "booking"),

("Whats the best deal for a 7 day holiday in Turkey", "booking"),
("I wanna book flights for Eid holidays", "booking"),
("Get me flights with no stopovers to Oman", "booking"),
("Check any flights today under 200 please", "booking"),
("Looking for hotel near Marina Bay from 5 to 10 July", "booking"),
("Book me a flex ticket I can change later", "booking"),
("I want a multi city trip London Dubai Karachi", "booking"),
("Need a one way flight to Canada next month", "booking"),

("Search for flights from Glasgow to Dubai in April", "booking"),
("Find cheapest day to fly to Istanbul in May", "booking"),
("Can you book a flight and hotel combo for Paris", "booking"),
("I want first class tickets to New York", "booking"),
("Any good prices for Maldives in summer", "booking"),
("Please book me on Emirates only", "booking"),
("I need a room with breakfast included", "booking"),
("Check if there are promo fares to Bahrain", "booking"),

("Find me flights after 6pm to Rome", "booking"),
("I need tickets for two adults and one child", "booking"),
("Looking for a cheap one way flight to Nigeria", "booking"),
("Book my trip for mid March exact date flexible", "booking"),
("Show me flights with 2 checked bags", "booking"),
("Find routes avoiding long layovers", "booking"),
("Need last minute deal for tonight", "booking"),
("I wanna fly from any London airport to Dubai", "booking"),

("Check hotel availability near Dubai Mall", "booking"),
("Book me whatever is cheapest for next Friday", "booking"),
("Need early morning flight to Tunisia", "booking"),
("Find direct flights only to Rome", "booking"),
("Looking for January flights to Jeddah for Umrah", "booking"),
("Need group booking for 10 people", "booking"),
("Find me flights returning before Sunday night", "booking"),
("I want to book a trip with 5 star hotel", "booking"),

("Search flexible tickets to Turkey", "booking"),
("I want flights with free cancellation", "booking"),
("Check any cheap flights from UK to anywhere", "booking"),
("Book 2 business class seats for next Thursday", "booking"),
("Find me a room with sea view", "booking"),
("Need honeymoon package options", "booking"),
("Can u find me a ticket to Turkey in March", "booking"),
("I need a flight from Manchester to Jeddah on Friday morning", "booking"),


# =========================================================================
# TICKET_CHANGE (64 examples)
# =========================================================================
("I need to change my flight date", "ticket_change"),
("Can I get a refund for my cancelled flight", "ticket_change"),
("I want to change my ticket to next week", "ticket_change"),
("Please move my return flight to 15 March", "ticket_change"),
("My name is wrong on the ticket can you fix it", "ticket_change"),
("I booked the wrong date need to update it", "ticket_change"),
("Can you cancel my booking", "ticket_change"),
("I want compensation for my delayed flight", "ticket_change"),

("I missed my flight what do I do now", "ticket_change"),
("Please rebook me on the next available flight", "ticket_change"),
("Can you shift my flight from morning to evening", "ticket_change"),
("I need to upgrade my seat to business", "ticket_change"),
("How do I change the passenger name", "ticket_change"),
("I want a refund airline changed the schedule", "ticket_change"),
("Cancel only my outward flight", "ticket_change"),
("I need to add baggage to my existing booking", "ticket_change"),

("Can you change my departure airport", "ticket_change"),
("I want to change only the return date", "ticket_change"),
("My booking shows wrong DOB need correction", "ticket_change"),
("The airline postponed my flight refund me", "ticket_change"),
("I want to upgrade to premium economy", "ticket_change"),
("Can you correct spelling of my last name", "ticket_change"),
("Please cancel everything and give refund", "ticket_change"),
("I want to modify my ticket for an earlier flight", "ticket_change"),

("Rebook me free of charge the delay was 3 hours", "ticket_change"),
("I bought the wrong destination can you fix it", "ticket_change"),
("I want an open ticket instead of fixed dates", "ticket_change"),
("My flight was rescheduled what are my options", "ticket_change"),
("Change my seat to window seat", "ticket_change"),
("Need to update passport number on my booking", "ticket_change"),
("Can you add a meal request to my ticket", "ticket_change"),
("I want to cancel the whole trip", "ticket_change"),

("Flight got cancelled rebook me ASAP", "ticket_change"),
("I need a refund for my no show", "ticket_change"),
("Can I move my flight to earlier today", "ticket_change"),
("I want my ticket fully refunded", "ticket_change"),
("Update the spelling of my first name", "ticket_change"),
("I need to modify travel dates because of work", "ticket_change"),
("Can you change my stopover city", "ticket_change"),
("Please postpone my flight to next month", "ticket_change"),

("Add another passenger to my booking", "ticket_change"),
("I accidentally booked 2025 instead of 2026", "ticket_change"),
("I need to switch to a direct flight", "ticket_change"),
("Please change my seat to aisle", "ticket_change"),
("I want refund for baggage I didnt get", "ticket_change"),
("Can you remove my infant from the booking", "ticket_change"),
("Change my ticket from economy to business", "ticket_change"),
("Missed the first leg can I still take return", "ticket_change"),

("Cancel the ticket but keep the hotel booking", "ticket_change"),
("My visa got delayed I need to change dates", "ticket_change"),
("Update my contact number on the booking", "ticket_change"),
("Add priority boarding to my ticket", "ticket_change"),
("Transfer my booking to another person", "ticket_change"),
("I need to adjust flight times", "ticket_change"),
("Change my connecting flight to shorter layover", "ticket_change"),
("Want to request wheelchair service", "ticket_change"),

("Airline changed aircraft want refund", "ticket_change"),
("Please apply for cancellation refund", "ticket_change"),
("Change child ticket to infant ticket", "ticket_change"),
("Remove one segment from my booking", "ticket_change"),
("Need to add extra luggage to existing ticket", "ticket_change"),
("My name is spelled wrong on the ticket", "ticket_change"),
("I missed my flight what can I do", "ticket_change"),
("I want to move my return flight to next week", "ticket_change"),


# =========================================================================
# FLIGHT_INFO (64 examples)
# =========================================================================
("How much baggage can I take", "flight_info"),
("Can I choose my seat in advance", "flight_info"),
("Whats the check in time for international flights", "flight_info"),
("Does Qatar Airways have WiFi", "flight_info"),
("Is food included on Emirates flights", "flight_info"),
("How long is the layover in Doha", "flight_info"),
("Can I carry medicine in hand luggage", "flight_info"),
("Is there free meal service on this flight", "flight_info"),

("Do I need to print my boarding pass", "flight_info"),
("Is online check in available", "flight_info"),
("What is the baggage limit for economy class", "flight_info"),
("Can I take two handbags", "flight_info"),
("Are power outlets available on the plane", "flight_info"),
("Does the airline offer halal meals", "flight_info"),
("How early should I be at the airport", "flight_info"),
("Is my laptop allowed in cabin bag", "flight_info"),

("Whats the liquid limit for hand luggage", "flight_info"),
("Does Turkish Airlines allow free seat selection", "flight_info"),
("How big can my suitcase be", "flight_info"),
("Will I need to recheck bags during transit", "flight_info"),
("Is transit visa needed for Doha layover", "flight_info"),
("Do infants get baggage allowance", "flight_info"),
("Is priority boarding available", "flight_info"),
("Are meals free on long flights", "flight_info"),

("Can I take my own snacks on board", "flight_info"),
("Is WiFi paid or free", "flight_info"),
("How strict is the weight limit", "flight_info"),
("Can I bring a stroller to the gate", "flight_info"),
("Does this flight offer entertainment screens", "flight_info"),
("Do I need to pick up bags between connecting flights", "flight_info"),
("What is the allowed carry on size", "flight_info"),
("Is there a limit for power banks", "flight_info"),

("What terminal does Qatar Airways fly from", "flight_info"),
("Is check in online or only at airport", "flight_info"),
("Does my fare include meals", "flight_info"),
("Can I travel with my pet", "flight_info"),
("Are wheelchair services free", "flight_info"),
("How do I request special meals", "flight_info"),
("Is my flight refundable", "flight_info"),
("Does Emirates allow 30kg baggage", "flight_info"),

("Can I upgrade at the airport", "flight_info"),
("Is there WiFi on board", "flight_info"),
("Do I need to print my ticket", "flight_info"),
("Is transit through Dubai allowed without visa", "flight_info"),
("Can I carry perfume in hand luggage", "flight_info"),
("How long before the flight does boarding close", "flight_info"),
("Are overhead bins first come first serve", "flight_info"),
("Do I need COVID documents", "flight_info"),

("Is water allowed after security", "flight_info"),
("Does my fare include seat selection", "flight_info"),
("Is there in flight entertainment", "flight_info"),
("Can I check in online with group booking", "flight_info"),
("Do connecting flights include meals", "flight_info"),
("Is there a dress code on flights", "flight_info"),
("Can I take gifts in my baggage", "flight_info"),
("What happens if my luggage is overweight", "flight_info"),

("Does the airline provide blankets", "flight_info"),
("Are there USB ports at every seat", "flight_info"),
("How early can I drop bags", "flight_info"),
("Can I select seats next to each other", "flight_info"),
("Are tablets allowed in cabin", "flight_info"),
("What are the cabin baggage rules", "flight_info"),
("Can I carry my laptop onboard", "flight_info"),
("Whats the weight limit for checked bags", "flight_info"),


# =========================================================================
# CLARIFICATION_ORIGIN (64 examples)
# =========================================================================
("nationality", "clarification_origin"),
("from there", "clarification_origin"),
("my country", "clarification_origin"),
("where im from", "clarification_origin"),
("citizen", "clarification_origin"),
("passport", "clarification_origin"),
("i live there", "clarification_origin"),
("thats my home", "clarification_origin"),
("origin", "clarification_origin"),
("im from there", "clarification_origin"),

("thats where i live", "clarification_origin"),
("my homeland", "clarification_origin"),
("born there", "clarification_origin"),
("i was born there", "clarification_origin"),
("home country", "clarification_origin"),
("where i was born", "clarification_origin"),
("my passport country", "clarification_origin"),
("i am from there", "clarification_origin"),
("thats my nationality", "clarification_origin"),
("where i come from", "clarification_origin"),

("im originally from there", "clarification_origin"),
("thats my origin", "clarification_origin"),
("i grew up there", "clarification_origin"),
("that's my birthplace", "clarification_origin"),
("thats where i come from", "clarification_origin"),
("thats where i was raised", "clarification_origin"),
("my birth country", "clarification_origin"),
("where i was raised", "clarification_origin"),
("its my origin country", "clarification_origin"),
("my home place", "clarification_origin"),

("that is my origin not destination", "clarification_origin"),
("thats the place im from", "clarification_origin"),
("im telling you my origin", "clarification_origin"),
("its my home nation", "clarification_origin"),
("thats my homeland country", "clarification_origin"),
("i belong to that country", "clarification_origin"),
("its the country i was born in", "clarification_origin"),
("the country where i grew up", "clarification_origin"),
("my home city is there", "clarification_origin"),
("the place i was born", "clarification_origin"),

("yes thats where im from", "clarification_origin"),
("yes thats my origin country", "clarification_origin"),
("it is my passport country", "clarification_origin"),
("thats my nationality origin", "clarification_origin"),
("the country listed on my passport", "clarification_origin"),
("thats my homebase", "clarification_origin"),
("i originate from there", "clarification_origin"),
("its where im originally from", "clarification_origin"),
("yes thats my origin", "clarification_origin"),
("thats my country of birth", "clarification_origin"),

("thats where i grew up", "clarification_origin"),
("that is my home origin", "clarification_origin"),
("the place i originate from", "clarification_origin"),
("my background country", "clarification_origin"),
("my origin place", "clarification_origin"),
("my roots are there", "clarification_origin"),
("i come from that country", "clarification_origin"),
("it's my native country", "clarification_origin"),
("thats where my family is from", "clarification_origin"),
("my residence is there", "clarification_origin"),
("i reside there", "clarification_origin"),
("my home base is there", "clarification_origin"),
("where my passport says", "clarification_origin"),
("the country on my id", "clarification_origin"),


# =========================================================================
# CLARIFICATION_DESTINATION (64 examples)
# =========================================================================
("travel", "clarification_destination"),
("going there", "clarification_destination"),
("destination", "clarification_destination"),
("visiting", "clarification_destination"),
("traveling", "clarification_destination"),
("travelling", "clarification_destination"),
("want to go there", "clarification_destination"),
("where im going", "clarification_destination"),
("thats where i want to visit", "clarification_destination"),
("trip", "clarification_destination"),

("holiday", "clarification_destination"),
("vacation", "clarification_destination"),
("going to visit", "clarification_destination"),
("planning to go", "clarification_destination"),
("want to travel there", "clarification_destination"),
("thats my destination", "clarification_destination"),
("where i want to go", "clarification_destination"),
("i want to visit there", "clarification_destination"),
("flying there", "clarification_destination"),
("headed there", "clarification_destination"),

("yes im going there", "clarification_destination"),
("thats the place im traveling to", "clarification_destination"),
("i mean my destination", "clarification_destination"),
("im referring to my destination", "clarification_destination"),
("that’s my final stop", "clarification_destination"),
("its the country i plan to visit", "clarification_destination"),
("the place im going to", "clarification_destination"),
("yes thats where i want to go", "clarification_destination"),
("thats the destination country", "clarification_destination"),
("thats the place i will visit", "clarification_destination"),

("thats where i will travel", "clarification_destination"),
("my intended destination", "clarification_destination"),
("my travel destination", "clarification_destination"),
("the place im headed to", "clarification_destination"),
("that's the country im visiting", "clarification_destination"),
("the country i want to go to", "clarification_destination"),
("yes thats where im traveling", "clarification_destination"),
("my trip is to that place", "clarification_destination"),
("thats where i want to fly", "clarification_destination"),
("yes that location", "clarification_destination"),

("the country i plan to go to", "clarification_destination"),
("that is my chosen destination", "clarification_destination"),
("that's the place i will travel to", "clarification_destination"),
("im traveling to that country", "clarification_destination"),
("thats my visit location", "clarification_destination"),
("my holiday spot is there", "clarification_destination"),
("thats where my trip is", "clarification_destination"),
("where i intend to travel", "clarification_destination"),
("yes thats my travel destination", "clarification_destination"),
("im going to that place", "clarification_destination"),

("im traveling there next", "clarification_destination"),
("that is the place im flying to", "clarification_destination"),
("im heading there soon", "clarification_destination"),
("my journey is to that country", "clarification_destination"),
("i will be going there", "clarification_destination"),
("my travel plan is for that place", "clarification_destination"),
("yes thats the country im going to", "clarification_destination"),
("thats exactly where im going", "clarification_destination"),
("that is the trip location", "clarification_destination"),
("the place im about to visit", "clarification_destination"),
("thats the place i booked for", "clarification_destination"),
("my flight is to there", "clarification_destination"),
("the place i have tickets for", "clarification_destination"),
("my vacation spot", "clarification_destination"),

]


# =========================================================================
# Labels and mappings
# =========================================================================

LABELS = ["casual", "visa_query", "follow_up", "booking", "ticket_change", "flight_info", "clarification_origin", "clarification_destination"]
LABEL_TO_ID = {label: i for i, label in enumerate(LABELS)}
ID_TO_LABEL = {i: label for i, label in enumerate(LABELS)}

# Verify counts when run directly
if __name__ == "__main__":
    from collections import Counter
    counts = Counter(label for _, label in TRAINING_DATA)
    print("Training data created:")
    for label in LABELS:
        print(f"  {label}: {counts[label]}")
    print(f"  TOTAL: {len(TRAINING_DATA)}")
